# Generated by Django 4.2 on 2023-04-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('category_l1', models.CharField(max_length=50)),
                ('category_l2', models.CharField(max_length=50)),
                ('upc', models.CharField(max_length=50)),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
